# -*- coding: utf-8 -*-
"""Probability Density Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zn6jBSH4ZQ_FAGNxI_juGXvbMgPpxkT7
"""

# Install if needed:
# !pip install pandas numpy matplotlib seaborn torch scikit-learn kaggle

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.neighbors import KernelDensity

import pandas as pd
import numpy as np

# Load dataset safely
df = pd.read_csv("data.csv", encoding='latin-1', low_memory=False)

# Clean column names
df.columns = df.columns.str.strip().str.lower()

# Extract NO2 (correct column)
x = df['no2'].dropna().values

# Normalize
x = (x - np.mean(x)) / np.std(x)

print("Data shape:", x.shape)
print("Sample values:", x[:5])

# Replace with your roll number
r = 102303048

a_r = 0.5 * (r % 7)
b_r = 0.3 * ((r % 5) + 1)

def transform(x):
    return x + a_r * np.sin(b_r * x)

z = transform(x)

# Convert to tensor
z_tensor = torch.tensor(z, dtype=torch.float32).view(-1, 1)

class Generator(nn.Module):
    def __init__(self, latent_dim=1):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, z):
        return self.model(z)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(1, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

latent_dim = 1
lr = 0.0002
epochs = 3000
batch_size = 128

G = Generator(latent_dim)
D = Discriminator()

criterion = nn.BCELoss()
optimizer_G = optim.Adam(G.parameters(), lr=lr)
optimizer_D = optim.Adam(D.parameters(), lr=lr)

for epoch in range(epochs):

    idx = np.random.randint(0, z_tensor.size(0), batch_size)
    real_data = z_tensor[idx]

    # Labels
    real_labels = torch.ones(batch_size, 1)
    fake_labels = torch.zeros(batch_size, 1)

    # --- Train Discriminator ---
    noise = torch.randn(batch_size, latent_dim)
    fake_data = G(noise)

    D_real = D(real_data)
    D_fake = D(fake_data.detach())

    loss_D = criterion(D_real, real_labels) + criterion(D_fake, fake_labels)

    optimizer_D.zero_grad()
    loss_D.backward()
    optimizer_D.step()

    # --- Train Generator ---
    noise = torch.randn(batch_size, latent_dim)
    fake_data = G(noise)

    D_fake = D(fake_data)
    loss_G = criterion(D_fake, real_labels)

    optimizer_G.zero_grad()
    loss_G.backward()
    optimizer_G.step()

    if epoch % 500 == 0:
        print(f"Epoch {epoch} | D Loss: {loss_D.item():.4f} | G Loss: {loss_G.item():.4f}")

num_samples = 5000
noise = torch.randn(num_samples, latent_dim)

generated_samples = G(noise).detach().numpy()
real_samples = z_tensor.numpy()

kde = KernelDensity(kernel='gaussian', bandwidth=0.2)
kde.fit(generated_samples)

z_range = np.linspace(min(z), max(z), 1000).reshape(-1, 1)
log_density = kde.score_samples(z_range)

pdf = np.exp(log_density)

plt.figure(figsize=(8,5))

# Real histogram
plt.hist(real_samples, bins=50, density=True, alpha=0.5, label='Real z')

# GAN KDE
plt.plot(z_range, pdf, label='GAN Estimated PDF', linewidth=2)

plt.legend()
plt.title("PDF Approximation using GAN")
plt.xlabel("z")
plt.ylabel("Density")
plt.show()